version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: notes-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/notes
      DB_USERNAME: admin
      DB_PASSWORD: postgres
      JWT_SECRET: d164aa1c9cbcb828a2b6cc1538abc066b47d132a838ecc25bd692df4373c6eed=
    restart: unless-stopped

volumes:
  postgres-data: