server:
  port: 8080
spring:
  application:
    name: Notes
  datasource:
    url: jdbc:postgresql://localhost:5432/notes
    password: admin
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    root: info
    org:
      springframework:
        web: info
      hibernate: info

app:
  jwt:
    secret: d164aa1c9cbcb828a2b6cc1538abc066b47d132a838ecc25bd692df4373c6eed
    expirationMs: 3600000
  ratelimiting:
    enabled: true
    limit: 100
    duration: 60