server:
  port: 8080
spring:
  application:
    name: Notes
  datasource:
    url: jdbc:postgresql://localhost:5432/notes
    password: admin
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



